steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/${CI_REPO_NAME%%-service}
      tags: latest
      platforms: linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [master]
